/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.PracticalJava;

public class App {
    
    public static void main(String[] args) {
        vertebrates vb = new vertebrates("felis catus",20,"obligate carnivores","warm");
        
        System.out.print(vb.getScientificname()+"\n"+vb.getLifespan()+"\n"+vb.getModeofNutrition()+"\n"+vb.getBloodtype());
    }
}
